language: bash
sudo: required

script:
    - echo "Downloading jq."
    - sudo apt-get install jq -y
    - echo "Making connection using github api"
    - curl -H Authorization: token $OAUTH https://api.github.com/users/hemanth22/gists
    - backupgist.sh
    - chmod 777 backupgist.sh
    - ./backupgist.sh
    - cat gist.backup

after_failure:
    #- set -x
    - wget -O createIssue.sh https://git.io/CreateIssue
    - chmod 777 createIssue.sh
    - ./createIssue.sh

notifications:
 slack:
   rooms:
     - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#mygitrepos
